# Generated by Django 3.2.5 on 2021-07-20 22:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('admin_panel', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Purchase_Details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Bill_no', models.IntegerField()),
                ('date_pur', models.DateTimeField()),
                ('party', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='admin_panel.partydetails')),
            ],
            options={
                'db_table': 'Purchase_details',
            },
        ),
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('salse_rate', models.IntegerField()),
                ('purchase_rate', models.IntegerField()),
                ('offer_rate', models.IntegerField()),
                ('quantity', models.IntegerField()),
                ('min_quantity', models.IntegerField()),
                ('offer_qty', models.IntegerField()),
                ('pro', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='admin_panel.products')),
                ('pur', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='Purchase.purchase_details')),
            ],
            options={
                'db_table': 'Stock',
            },
        ),
    ]
