# Generated by Django 3.2.5 on 2021-07-20 22:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('admin_panel', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice_Details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('credit', models.IntegerField()),
                ('debit', models.IntegerField()),
                ('total', models.BigIntegerField()),
                ('invoice_number', models.IntegerField()),
                ('date_In', models.DateTimeField()),
                ('party', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='admin_panel.partydetails')),
            ],
            options={
                'db_table': 'InvoiceDetails',
            },
        ),
        migrations.CreateModel(
            name='Sales_Details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('salse_quantity', models.IntegerField()),
                ('Invoice_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='salles.invoice_details')),
                ('pro', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='admin_panel.products')),
            ],
            options={
                'db_table': 'SalseDetails',
            },
        ),
    ]
